<?php

use Abiliomp\Pkuatia\Config;
use Abiliomp\Pkuatia\Core\Autofactura;
use Abiliomp\Pkuatia\Core\DocumentoElectronico;
use Abiliomp\Pkuatia\Core\Factura;
use Abiliomp\Pkuatia\Core\NotaCredito;
use Abiliomp\Pkuatia\Core\NotaDebito;
use Abiliomp\Pkuatia\Core\NotaRemision;

require '../vendor/autoload.php'; // Include the Composer autoloader

error_reporting(E_ALL);
ini_set('display_errors', 1);

// $documento = new DocumentoElectronico();
// var_dump($documento);

// $fe = new Factura();
// var_dump($fe);

// $afe = new Autofactura();
// var_dump($afe);

// $nc = new NotaCredito();
// var_dump($nc);

// $nd = new NotaDebito();
// var_dump($nd);

// $nr = new NotaRemision();
// var_dump($nr);